target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
#   pod 'MapboxCoreNavigation', '~> 2.13'
#   pod 'MapboxNavigation', '~> 2.13'
  pod 'MapboxMaps', '10.14.0'
  pod 'shared', :path => '/Users/panosstylianou/AndroidStudioProjects/TestKMM/shared'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        # Here you can specify which pods you want to change the deployment target for
        if ['MapboxMobileEvents', 'Solar-dev'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0' # or another version
            end
        end
    end
#     installer.pods_project.build_configurations.each do |config|
#         config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "x86_64"
#     end
end
